# Generated by Django 5.2.17 on 2026-09-04 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='درباره آرایشگر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل آرایشگر',
                'verbose_name_plural': 'پروفایل\u200cهای آرایشگران',
            },
        ),
        migrations.CreateModel(
            name='BarberServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.PositiveIntegerField(blank=True, help_text='در صورت خالی بودن، قیمت پایه خدمت اعمال می\u200cشود.', null=True, verbose_name='قیمت اختصاصی (تومان)')),
                ('custom_duration_minutes', models.PositiveIntegerField(blank=True, help_text='در صورت خالی بودن، مدت زمان پیش\u200cفرض اعمال می\u200cشود.', null=True, verbose_name='مدت زمان اختصاصی (دقیقه)')),
                ('start_time', models.TimeField(blank=True, help_text='در صورت خالی بودن، تابع ساعات کاری عمومی آرایشگر است.', null=True, verbose_name='ساعت شروع ارائه خدمت')),
                ('end_time', models.TimeField(blank=True, help_text='در صورت خالی بودن، تابع ساعات کاری عمومی آرایشگر است.', null=True, verbose_name='ساعت پایان ارائه خدمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت ارائه')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='barbers.barbermodel', verbose_name='آرایشگر')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='salon_services.servicemodel', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'خدمت آرایشگر',
                'verbose_name_plural': 'خدمات آرایشگران',
                'unique_together': {('barber', 'service')},
            },
        ),
        migrations.CreateModel(
            name='WorkingHoursModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('slot_duration', models.PositiveIntegerField(default=30, verbose_name='مدت زمان هر اسلات (دقیقه)')),
                ('is_closed', models.BooleanField(default=False, verbose_name='تعطیل است')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='barbers.barbermodel', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
                'unique_together': {('barber', 'day_of_week')},
            },
        ),
    ]
