# Generated by Django 5.2.17 on 2026-09-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinghoursmodel',
            unique_together=set(),
        ),
    ]
