# Generated by Django 5.2.17 on 2026-09-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل مشتری',
                'verbose_name_plural': 'پروفایل\u200cهای مشتریان',
            },
        ),
        migrations.CreateModel(
            name='CustomerHairstyleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customers/hairstyles/', verbose_name='تصویر مدل مو')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان / نام مدل مو')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات و یادداشت آرایشگر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hairstyles', to='customers.customermodel', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'مدل موی مشتری',
                'verbose_name_plural': 'مدل\u200cهای موی مشتریان',
                'ordering': ['-created_at'],
            },
        ),
    ]
