# Generated by Django 5.2.17 on 2026-08-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'مشتری'), ('BARBER', 'آرایشگر'), ('MANAGER', 'مدیر')], default='CUSTOMER', max_length=20, verbose_name='نقش کاربر'),
        ),
    ]
