# Generated by Django 5.2.17 on 2026-09-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('base_price', models.PositiveIntegerField(verbose_name='قیمت پایه (تومان)')),
                ('default_duration_minutes', models.PositiveIntegerField(default=45, verbose_name='مدت زمان پیش\u200cفرض (دقیقه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
            ],
            options={
                'verbose_name': 'خدمت سالن',
                'verbose_name_plural': 'خدمات سالن',
            },
        ),
    ]
