from .dashboard_view import DashboardView
from .admin_login_view import AdminLoginView
from .salon_services_list_view import SalonServicesListView
from .save_salon_service_view import SaveSalonServiceView