# Generated by Django 5.2.17 on 2026-09-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_used', models.BooleanField(default=False, verbose_name='مصرف شده')),
            ],
            options={
                'verbose_name': 'کد یکبار مصرف',
                'verbose_name_plural': 'کدهای یکبار مصرف',
                'ordering': ['-created_at'],
            },
        ),
    ]
