from .send_otp_view import SendOTPView
from .verify_otp_view import VerifyOTPView
from .otp_page_view import OTPPageView
from .select_barber_and_service_view import SelectBarberAndServiceView
from .select_datetime_view import SelectDatetimeView
from .review_booking_view import ReviewBookingView