# Generated by Django 5.2.17 on 2026-09-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        ('customers', '0001_initial'),
        ('salon_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ نوبت')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت ثبت\u200cشده (تومان)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('CONFIRMED', 'تایید شده'), ('COMPLETED', 'انجام شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20, verbose_name='وضعیت نوبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='barbers.barbermodel', verbose_name='آرایشگر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.customermodel', verbose_name='مشتری')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='salon_services.servicemodel', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'رزرو نوبت',
                'verbose_name_plural': 'رزروهای نوبت',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
