# Generated by Django 5.2.17 on 2026-09-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_alter_workinghoursmodel_unique_together'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='service',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='barbers.barberservicemodel', verbose_name='خدمات انتخاب\u200cشده'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='total_duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع مدت زمان (دقیقه)'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع قیمت ثبت\u200cشده (تومان)'),
        ),
    ]
